server:
  port: 8080

spring:
  profiles:
    active: development

jwt:
  expiration: 86400000 # 24 hours in milliseconds

user:
  timezone: Asia/Kolkata

# SpringDoc OpenAPI configuration
springdoc:
  api-docs:
    enabled: true  # Enable to access Swagger UI resources
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    url: /openapi/openapi.yml  # Point to your static file
    config-url: /v3/api-docs/swagger-config
  show-actuator: false
